# comment the expected version on PR

name: Comment Expected Release Version

on:
  pull_request:
    branches:
    - "master"

jobs:
  comment-version:
    uses: openedx/.github/.github/workflows/expected-release-version.yml@huniafatima/release-expected-version-workflow