# comment the expected version on PR

name: Comment Expected Release Version

on:
  pull_request:
    branches:
    - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Preview semantic-release version
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
      run: npx semantic-release@17 --dry-run --no-ci