# comment the expected version on PR

name: Comment Expected Release Version

on:
  pull_request:
    branches:
    - "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
    - name: Install dependencies
      run: npm ci
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Run semantic-release in dry-run mode
      run: npx semantic-release --dry-run > output.log

    - name: Extract next version
      id: extract_version
      run: |
        VERSION=$(grep -oP '(?<=next release version: )\S+' output.log)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Comment version on PR
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Next release version: ${{ env.VERSION }}